### DISCUSSION TITLE
How can I expand has_many field?

### DISCUSSION THREAD

**Discussion by HeppokoNeet** [railsadminteam/rails_admin#3512] [Q&A]
<img width="519" alt="スクリーンショット 2022-02-02 16 36 58 のコピー" src="https://user-images.githubusercontent.com/36767393/152112668-42edd88f-8fd7-4be5-a061-80bbee0953b5.png">

I want to expand has_many field.
When I try this code 
```
field :evaluations do
        required true
        html_attributes rows: 30, cols: 50
      end
```

it doesn't work.
seems working only normal field.

How can I do that?

**Comment by codealchemy** [comment]
For cases where the `form_filtering_multiselect` is used (which is what appears to be the case :point_up:), I don't believe `html_attributes` will have any effect (since the widget overrides [the `select` in the template that those attributes are passed to](https://github.com/railsadminteam/rails_admin/blob/e5bb7ba712a00ede56ffc8a547b36b13bd72a9ee/app/views/rails_admin/main/_form_filtering_multiselect.html.erb#L41)) - you'd need to look at updating the [CSS](https://github.com/railsadminteam/rails_admin/blob/master/src/rails_admin/styles/filtering-multiselect.scss) for that widget.

ex. to adjust the width / height of the multiselect (globally):

```scss
.ra-multiselect > .ra-multiselect-column > .wrapper > select {
  min-width: 400px; // default 200px
  min-height: 200px; // default 120px
}
```
