### ISSUE TITLE
Basic CSS layout overrides

### ISSUE THREAD

**Issue by galtenberg** [railsadminteam/rails_admin#1209]
I could use some guidance on adding some basic CSS/SASS overrides.

Trying to change bootstrap span widths (default span3 seems too wide, span9 too narrow):

``` css
.row-fluid .span3 { width: 12% }
.row-fluid .span9 { width: 85% }
```

It seems that a rails_admin.css file is looked for, but adding that to assets path just causes the project's rails_admin.css to be ignored (ruining all styles).

Looked through the wiki, issues, etc, sorry if this has already been covered.
