### ISSUE TITLE
How to translate enum?

### ISSUE THREAD

**Issue by Napoleonyjl** [railsadminteam/rails_admin#1815]
Hi everyone! I have problem on translating enum content (gender).
The .rb file in app/models folder is like this:

```
            class AiitMember < ActiveRecord::Base
              attr_accessible :birthday, :kana_name, :gender, :memo, :name

              has_one :privacy
              has_many :prospects
              has_many :exam_lists
              has_many :student_lists

              rails_admin do

                    list do
                        field :name
                        field :kana_name
                        field :birthday
                        field :gender, :enum do
                            enum do
                              ['male', 'female']
                            end
                         end
                        field :memo
                    end

                    edit do
                        field :name
                        field :kana_name
                        field :birthday
                        field :gender, :enum do
                            enum do
                              ['male', 'female']
                            end
                         end
                        field :memo
                    end
              end

            end
```

and I add translate content everywhere in translation_ja.yml and ja.yml but none of them work. (For test, I just make them upper case to 'MALE' and 'FEMALE.)

Here is the translation_ja.yml.

```
  ja:
      enums:
        aiit_member:
          gender:
            female: FEMALE
            male: MALE

      activerecord:
        enums:
          aiit_member:
            gender:
              male: MALE
              female: FEMALE
            genders:
              female: FEMALE
              male: MALE

        models:
          aiit_member: AIIT会員(Master)  #g
          association_pbl: association_pbl  #g
          association_student: association_student  #g
          association_teacher: association_teacher  #g
          exam_list: 受験情報  #g
          guarantor: 保証人  #g
          status_record: 身分異動  #g
          tuition: 授業料関係 #g
          privacy: 個人情報  #g
          prospect: 見込み学生  #g
          user: ユーザー情報  #g
          student_list: 学生情報  #g

        enums:
          aiit_member:
            gender:
              female: FEMALE
              male: MALE
            genders:
              female: FEMALE
              male: MALE

        attributes:
          aiit_member:
            birthday: 生年月日  #g
            name: 名前  #g
            kana_name: カナ氏名  #g
            gender: 性別  #g
            memo: 備考 #g
            exam_lists: 受験情報  
            status_record: 身分異動  
            privacy: 個人情報  
            prospects: 見込み学生
            student_lists: 学生情報 
            enums:
              gender:
                male: MALE
                female: FEMALE
              genders:
                female: FEMALE
                male: MALE


          association_pbl:
            association_students: association_students  #g
            association_teacher: :activerecord.models.association_teacher  #g
            name: name  #g

          association_student:
            association_pbl: :activerecord.models.association_pbl  #g
            name: name  #g

          association_teacher:
            association_pbl: :activerecord.models.association_pbl  #g
            name: name  #g

          exam_list: 
            basic_knowledge: IT基礎知識  #g
            citizen_of_tokyo: 都民  #g
            decision_reason: 判定理由  #g
            exam_no: 受験番号  #g
            exam_year: 受験年度  #g
            examination: 入試  #g
            interview: 面接  #g
            memo: 備考  #g
            paper: 小論文  #g
            presentation: プレゼンテーション  #g
            result: 合否  #g
            review_flg: 事前審査有無  #g
            test_score: 合計点  #g
            aiit_member: AIIT会員

          guarantor:
            guarantor_address: 住所  #g
            name: 保証人氏名  #g
            guarantor_kana: 保証人カナ  #g
            relationship: 続柄区分  #g
            guarantor_tel: 電話 #g
            guarantor_zip: 郵便番号 #g
            memo: 備考 #g
            student_lists: 学生情報  #g

          status_record:
            absence_reason: 異動理由 #g
            absence_time: 休学期間 #g
            beginning: 開始時間 #g
            end: 終了時間 #g
            memo: 備考 #g
            status: 身分 #g
            student_list: 学生情報

          tuition:
            first_term_reduction: 前期減免 #g
            loan_amount: 貸与額 #g
            memo: 備考 #g
            scholarship_division: 奨学金区分 #g
            second_term_reduction: 後期減免 #g
            transfer_request: 振替依頼書 #g
            student_list: 学生情報

          student_list:
            PBL_1st: PBL前期 #g
            PBL_2nd: PBL後期 #g
            PBL_teacher: PBL担任 #g
            campus_email: 学内E-Mailアドレス #g
            classification: 種別 #g
            entrance_date: 入学年月日 #g
            grade: 学年 #g
            graduation_date: 終了予定日 #g
            memo: 備考 #g
            name: 学修番号 #g
            nationality: 国籍 #g
            program: クラス #g
            student_account: ユーザID #g
            study_period: 履修期間 #g
            visa:  在留資格 #g
            status_records: 身分異動  #g
            tuitions: 授業料関係 #g
            aiit_member: AIIT会員
            guarantor: 保証人

          privacy:
            address: 住所番地  #g
            birthday: 生年月日  #g
            block: 市区町村  #g
            building: 建物名・部屋番号  #g
            city: 都道府県  #g
            company: 勤務先  #g
            company_address: 勤務先住所  #g
            work_period: 勤務期間 #g
            department: 学部  #g
            stream: 文理 #g
            eng_name: 英字氏名  #g
            graduated_date: 卒業年度  #g
            new_graduates: 新卒 #g
            graduated_school: 卒業学校  #g
            kana_name: カナ氏名  #g
            mobile_email: 個人Mail（携帯）  #g
            pc_email: 個人Mail（PC）  #g
            mobile: 電話番号（携帯）  #g
            name: 漢字氏名  #g
            birthplace: 出身  #g
            occupation: 現職  #g
            gender: 性別  #g
            tel: 電話番号（自宅）  #g
            zip_code: 郵便番号  #g
            memo: 備考 #g
            aiit_member: AIIT会員


          prospect:
            event: イベント #g
            contact_unnecessary: 情報連絡不要  #g
            received_date: 受信日 #g
            wished_program: 希望専攻  #g
            wished_material: 希望資料  #g
            visited_date: 来場日  #g
            applikation: 出願 #g
            memo: 備考 #g
            aiit_member: AIIT会員

          user:
            current_sign_in_at: 今回ログインした日  #g
            current_sign_in_ip: 今回ログインしたIPアドレス  #g
            email: E-mailアドレス  #g
            password: パスワード  #g
            password_confirmation: パスワード確認  #g
            encrypted_password: 暗号化したパスワード  #g
            last_sign_in_at: 前回ログインした日  #g
            last_sign_in_ip: 前回ログインしたIPアドレス #g
            remember_created_at: ログインを記憶した日  #g
            reset_password_sent_at: パスワードリセットを送信した日  #g
            reset_password_token: パスワードリセットのトークン  #g
            sign_in_count: ログインした回数   #g
```

and here is ja.yml

```
  ja:
    date:
      abbr_day_names:
      - 日
      - 月
      - 火
      - 水
      - 木
      - 金
      - 土
      abbr_month_names:
      - 
      - 1月
      - 2月
      - 3月
      - 4月
      - 5月
      - 6月
      - 7月
      - 8月
      - 9月
      - 10月
      - 11月
      - 12月
      day_names:
      - 日曜日
      - 月曜日
      - 火曜日
      - 水曜日
      - 木曜日
      - 金曜日
      - 土曜日
      formats:
        default: ! '%Y/%m/%d'
        long: ! '%Y-%m-%d'
        short: ! '%m/%d'
      month_names:
      - 
      - 1月
      - 2月
      - 3月
      - 4月
      - 5月
      - 6月
      - 7月
      - 8月
      - 9月
      - 10月
      - 11月
      - 12月
      order:
      - :year
      - :month
      - :day
    datetime:
      distance_in_words:
        about_x_hours:
          one: 約1時間
          other: 約%{count}時間
        about_x_months:
          one: 約1ヶ月
          other: 約%{count}ヶ月
        about_x_years:
          one: 約1年
          other: 約%{count}年
        almost_x_years:
          one: 1年弱
          other: ! '%{count}年弱'
        half_a_minute: 30秒前後
        less_than_x_minutes:
          one: 1分以内
          other: ! '%{count}分以内'
        less_than_x_seconds:
          one: 1秒以内
          other: ! '%{count}秒以内'
        over_x_years:
          one: 1年以上
          other: ! '%{count}年以上'
        x_days:
          one: 1日
          other: ! '%{count}日'
        x_minutes:
          one: 1分
          other: ! '%{count}分'
        x_months:
          one: 1ヶ月
          other: ! '%{count}ヶ月'
        x_seconds:
          one: 1秒
          other: ! '%{count}秒'
      prompts:
        day: 日
        hour: 時
        minute: 分
        month: 月
        second: 秒
        year: 年
    errors: &errors
      format: ! '%{attribute}%{message}'
      messages:
        accepted: を受諾してください。
        blank: を入力してください。
        confirmation: と確認の入力が一致しません。
        empty: を入力してください。
        equal_to: は%{count}にしてください。
        even: は偶数にしてください。
        exclusion: は予約されています。
        greater_than: は%{count}より大きい値にしてください。
        greater_than_or_equal_to: は%{count}以上の値にしてください。
        inclusion: は一覧にありません。
        invalid: は不正な値です。
        less_than: は%{count}より小さい値にしてください。
        less_than_or_equal_to: は%{count}以下の値にしてください。
        not_a_number: は数値で入力してください。
        not_an_integer: は整数で入力してください。
        odd: は奇数にしてください。
        record_invalid: バリデーションに失敗しました。 %{errors}
        taken: はすでに存在します。
        too_long: は%{count}文字以内で入力してください。
        too_short: は%{count}文字以上で入力してください。
        wrong_length: は%{count}文字で入力してください。
      template:
        body: 次の項目を確認してください。
        header:
          one: ! '%{model}にエラーが発生しました。'
          other: ! '%{model}に%{count}個のエラーが発生しました。'
    helpers:
      select:
        prompt: 選択してください。
      submit:
        create: 登録する
        submit: 保存する
        update: 更新する
    number:
      currency:
        format:
          delimiter: ! ','
          format: ! '%n%u'
          precision: 0
          separator: .
          significant: false
          strip_insignificant_zeros: false
          unit: 円
      format:
        delimiter: ! ','
        precision: 3
        separator: .
        significant: false
        strip_insignificant_zeros: false
      human:
        decimal_units:
          format: ! '%n %u'
          units:
            billion: 十億
            million: 百万
            quadrillion: 千兆
            thousand: 千
            trillion: 兆
            unit: ''
        format:
          delimiter: ''
          precision: 3
          significant: true
          strip_insignificant_zeros: true
        storage_units:
          format: ! '%n%u'
          units:
            byte: バイト
            gb: ギガバイト
            kb: キロバイト
            mb: メガバイト
            tb: テラバイト
      percentage:
        format:
          delimiter: ''
      precision:
        format:
          delimiter: ''
    support:
      array:
        last_word_connector: と
        two_words_connector: と
        words_connector: と
    time:
      am: 午前
      formats:
        default: ! '%Y/%m/%d %H:%M:%S'
        long: ! '%Y-%m-%d-%H:%M:%S:%z'
        short: ! '%y/%m/%d %H:%M'
      pm: 午後
    # remove these aliases after 'activemodel' and 'activerecord' namespaces are removed from Rails repository
    activemodel:
      errors:
        <<: *errors
    activerecord:
      enums:
        aiit_member:
          gender:
            male: MALE
            female: FEMALE
          genders:
            female: FEMALE
            male: MALE
    male: MALE
    female: FEMALE
```

Where and how should I write the translate content?

**Comment by alexanderadam** [comment]
In case anyone came here from google:

I'm not sure whether I ran into a few bugs or just missed the proper documentation but I had some issues with translating active record enums and solved it this way:

override `parse_input_value` in an initializer because the mapping is not necessary at this place
```ruby
RailsAdmin::Config::Fields::Types::ActiveRecordEnum.class_eval do
  def parse_input_value(value)
    value
  end
end
```
define the fields with the proper caption or translation and the enum value
```ruby
config.model SomeModel do
  edit do
    field :the_enum_attribute, :enum do
      enum do
        array = SomeModel.the_enum_attributes.map do |k, _|
          [I18n.t("activerecord.attributes.some_model.the_enum_attributes.#{k}"), k]
        end
        Hash[array]
      end
    end
  end
end
```

copy [`_form_enumeration.html.haml`](https://github.com/sferik/rails_admin/blob/master/app/views/rails_admin/main/_form_enumeration.html.haml) to `app/views/rails_admin/main/_form_enumeration.html.haml` and replace `selected: field.form_value` with `selected: form.object.class.public_send(field.method_name.to_s.pluralize).invert[field.form_value]`

**Comment by omarzina** [comment]
In case anyone is still landing here from google, this worked for me (v3.1.1) to get an `enum` field translated in all views:

```ruby
class Model < ApplicationRecord
  enum :status, {active: 0, inactive: 1}
  rails_admin do
  # Edit form
    edit do
      field :status, :enum do
        enum do
          array = Model.statuses.map do |k, _|
            [I18n.t("attributes.statuses.#{k}"), k]
          end
          array.to_h
        end
      end
    end

  # show & list
    field :status, :enum do
      pretty_value do
        value ? I18n.t("attributes.statuses.#{value}") : "-"
      end
    end
  end
end
```

And the translation:
```yml
en:
  attributes:
    statuses:
      active: Active
      inactive: Inactive
```
