### ISSUE TITLE
Reconsider usage of badges for booelan.rb

### ISSUE THREAD

**Issue by carlesso** [railsadminteam/rails_admin#2131]
In [boolean.rb](https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/config/fields/types/boolean.rb) `badge-important` and `badge-success` are used for boolean background, but boostrap 3 does not support badge colors anymore

> We have differentiated the labels and badges with v3. The gist is that badges no longer have modifier classes and are purely meant as unread counters.
> 
> ￼> Dropped all modifier variations on badges, making it as neutral as possible, much like those of Mail.app on OS X.

Maybe should switch to `label` instead.

For anyone needing a quickfix in the meantime put this in `theming.css`

``` css
.badge-success {
  background-color: #5cb85c;
}
.badge-important {
  background-color: #d9534f;
}
```
