### ISSUE TITLE
Can't translate field names/labels

### ISSUE THREAD

**Issue by fernandomm** [railsadminteam/rails_admin#989]
Hi,

I'm trying to translate field names in rails admin but it's not working. Setting active record attributes should work, no?

Sample yml file:

```
pt-BR:
  activerecord:
    attributes:
      user:
        password: "Senha"
```

Even with this, when i try to create a new user, it still shows "Password" instead of "Senha".
